version: '3.7'

services:
  awesome:
    #build: ./app1
    image: deploymentstrategy_awesome:latest
    ports:
     - 8080
    environment:
     - SERVICE_PORTS=8080
    networks:
     - web
    deploy:
      resources:
        limits:
          memory: 256M
  proxy:
    image: haproxy:1.8
    depends_on:
      - awesome
    volumes:
      - ./usr/local/etc/haproxy:/usr/local/etc/haproxy
    ports:
      - 80:80
      - 70:70
    networks:
      - web
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  web:
    driver: overlay
