version: '3.7'

services:
  awesome:
    image: deploymentstrategy_awesome:latest
    ports:
     - 8080
    environment:
     - SERVICE_PORTS=8080
    networks:
     - web
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 256M
  proxy:
    image: haproxy:1.8
    depends_on:
      - awesome
      - awesome2
    volumes:
      - ./usr/local/etc/haproxy:/usr/local/etc/haproxy
    ports:
      - 80:80
      - 70:70
    networks:
      - web
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 256M
  awesome2:
    image: deploymentstrategy_awesome2:latest
    ports:
     - 10010
    environment:
     - SERVICE_PORTS=10010
    networks:
     - web
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 256M

networks:
  web:
    driver: overlay
